# Generated by Django 6.1.1 on 2026-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(db_index=True, help_text='Unique OPIS Truckstop ID from CSV', unique=True)),
                ('name', models.CharField(help_text='Truckstop name', max_length=255)),
                ('address', models.CharField(help_text='Street, exit, or highway address', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter US state code (e.g., TX, CA)', max_length=10)),
                ('rack_id', models.IntegerField(blank=True, help_text='Rack ID from source CSV if present', null=True)),
                ('price', models.DecimalField(decimal_places=4, help_text='Retail fuel price per gallon (USD)', max_digits=7)),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='Latitude coordinate in decimal degrees', null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='Longitude coordinate in decimal degrees', null=True)),
                ('geocode_precision', models.CharField(choices=[('address', 'Address / Intersection Match'), ('city_fallback', 'City Centroid Fallback'), ('unresolved', 'Unresolved')], default='address', help_text='Precision level of station coordinates', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this station is active for route optimization')),
                ('source', models.CharField(default='opis_csv', help_text='Source identifier for data lineage', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['station_id'],
                'indexes': [models.Index(fields=['state', 'is_active'], name='fuel_station_state_active_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_station_coords_idx')],
            },
        ),
    ]
